apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale
  template:
    metadata:
      labels:
        app: autoscale
    spec:
      containers:
        - name: autoscale-container
          image: autoscale-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
